version: '3.5'

services:
  legacy-db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: iogt
    volumes:
      - /var/lib/postgresql/data
      - ./legacy-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 54321:5432
