version: '3.5'

services:

  django:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: dc01
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: iogt
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: iogt.settings.docker_compose_dev
      COMMIT_HASH: asdfghjkl
      RAPIDPRO_BOT_USER_ID: 1
      RAPIDPRO_BOT_USER_USERNAME: rapidpro
      RAPIDPRO_BOT_USER_PASSWORD: 1234
      WAGTAILTRANSFER_SECRET_KEY: wagtailtransfer-secret-key
      WAGTAILTRANSFER_SOURCE_NAME: iogt_global
      WAGTAILTRANSFER_SOURCE_BASE_URL: https://example.com/wagtail-transfer/
      WAGTAILTRANSFER_SOURCE_SECRET_KEY: wagtailtransfer-source-secret-key
      BASE_URL: 'http://localhost:8000'
    command: bash -c "python manage.py load_po_files && python manage.py compilemessages && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - db

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.12.1'
    container_name: ec01
    environment:
      - discovery.type=single-node
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  db:
    image: postgres:alpine
    container_name: pc01
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: iogt
    volumes:
      - /var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  legacy-db:
    image: postgres:alpine
    container_name: lc01
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: iogt
    volumes:
      - /var/lib/postgresql/data
      - ./legacy-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 54321:5432

  tag-manager:
    image: gcr.io/cloud-tagging-10302018/gtm-cloud-image:stable
    container_name: tm01
    restart: unless-stopped
    environment:
      CONTAINER_CONFIG: '<server-side gtm container config>'
    ports:
      - 8080:8080

volumes:
  es-data01:
