version: '3.5'

services:
  django:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      DJANGO_SETTINGS_MODULE: iogt.settings.cypress
      COMMENT_MODERATION_CLASS: 'comments.clients.AlwaysApproveModerator'
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
