# Generated by Django 3.1.14 on 2022-09-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_delete_offline_app_page_and_create_offline_content_index_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hide_double_navbar_in_single_column_view',
            field=models.BooleanField(default=False),
        ),
    ]
