name: IoGT

on:
  push:
    branches:
      - develop
      - release/**
  pull_request:
    branches:
      - develop

jobs:

  django-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make test
      - uses: actions/upload-artifact@v2
        with:
          name: django-coverage-report
          path: htmlcov

  selenium-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make selenium-test
      - uses: actions/upload-artifact@v2
        with:
          name: django-coverage-report
          path: htmlcov

